version: '3.4'
services:
  k6:
    build: .
    # image: xk6-counter:latest
    container_name: xk6-counter
    volumes:
      - ./loadtests/counter.js:/loadtests/counter.js
#     working_dir: /k6/loadtests
    command: run /loadtests/counter.js
