version: 2.1
orbs:
 k6io: k6io/test@1.1.0
workflows:
 load_test:
   jobs:
     - k6io/test:
         cloud: true
         script: loadtests/performance-test.js
         arguments: --env K6_CLOUD_TOKEN=8b0b6b3d25626a9875a3028355542635a62246bc166a8538ef9de9e50222d803
