version: 2.1
orbs:
 k6io: k6io/test@1.1.0
workflows:
  load_test:
   jobs:
     - k6io/test:
         script: loadtests/performance-test.js
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - k6io/test