version: 2.1
orbs:
 k6io: k6io/test@1.1.0
workflows:
 load_test:
   jobs:
     - k6io/test:
         cloud: true
         script: loadtests/performance-test.js
         token: 51aeec43d8ef04dcfe24ba70d66ec9e3c0268b3ff70978659e0624dd37082b11
