version: 2
jobs:
 test:
   docker:
     - image: sparatan/k6-example-circleci-orb  # You can rebuild this image and push it to your docker hub account 
   steps:
     - checkout
     - setup_remote_docker:
         version: 19.03.13
     - run:  
         name: Execute tests on the docker image
         command: k6 run loadtests/performance-test.js  > /tmp/artifacts

     - store_artifacts:
         path: /tmp/artifacts
 
workflows:
 version: 2
 build-master:
   jobs:
     - test