# default: &defaults
#   parallelism: 1
#   working_directory: ~/my-project

# k6_performance_tests: &k6_performance_tests
#   run:
#     name: Running k6 tests
#     command: |
#       docker pull loadimpact/k6:latest
#       docker run -i -e K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN -e K6_CLOUD_PROJECT_ID=$K6_CLOUD_PROJECT_ID -v $HOME/my-project:/ci/ loadimpact/k6:latest cloud /ci/loadtests/performance-test.js

# version: 2
# jobs:
#   run_performance_tests:
#     <<: *defaults
#     machine: true
#     steps:
#       - checkout
#       - *k6_performance_tests

# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - run_performance_tests

version: 2.1
orbs:
  k6io: k6io/test@1.1.0
workflows:
  load_test:
    jobs:
      - k6io/test:
          cloud: true
          args: '--env K6_CLOUD_PROJECT_ID=$K6_CLOUD_PROJECT_ID K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN'
          script: loadtests/performance-test.js
          token: $K6_CLOUD_TOKEN
